twig:
    paths:
      '%kernel.project_dir%/templates': App
      '%kernel.project_dir%/vendor/sonata-project/admin-bundle/src/Resources/views': SonataAdminBundle
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    #        '%kernel.project_dir%/vendor/sonata-project/admin-bundle/src/Resources/views': 'SonataAdminBundle'